M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, July 19, 2023 10:45:18 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-19T10:45:18+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X17.784Y-28.188
X50.804Y-80.258
X66.044Y-29.458
T2
X4.0Y-4.0
X4.0Y-116.0
X84.0Y-4.0
X84.0Y-40.0
X84.0Y-116.0
T0
M30
