M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, March 19, 2023 11:13:46 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-19T23:13:46+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.7Y-1.11
X2.0Y-3.16
X2.6Y-1.16
T2
X0.1575Y-0.1575
X0.1575Y-4.5669
X3.3071Y-0.1575
X3.3071Y-1.5748
X3.3071Y-4.5669
T0
M30
